// Generated by scripts/neckline-bands.py. Do not edit by hand: re-run the
// script when a neckline image changes.
//
// For each neckline, the band its cuffs take: a straight run of its own arm,
// turned level and long enough to go round a sleeve in one piece. `length`
// and `depth` are its size as shares of the neckline image's width, so it
// is drawn at the neckline's own scale.

export type NecklineBand = { image: string; length: number; depth: number };

export const NECKLINE_BANDS: Record<string, NecklineBand> = {
  "/img/designs/necklines/nl01.png": { image: "/img/designs/necklines/nl01-band.png", length: 1.0512, depth: 0.0545 },
  "/img/designs/necklines/nl02.png": { image: "/img/designs/necklines/nl02-band.png", length: 1.1267, depth: 0.0289 },
  "/img/designs/necklines/nl03.png": { image: "/img/designs/necklines/nl03-band.png", length: 1.1767, depth: 0.0733 },
  "/img/designs/necklines/nl04.png": { image: "/img/designs/necklines/nl04-band.png", length: 1.1800, depth: 0.0200 },
  "/img/designs/necklines/nl05.png": { image: "/img/designs/necklines/nl05-band.png", length: 1.0214, depth: 0.0571 },
  "/img/designs/necklines/nl06.png": { image: "/img/designs/necklines/nl06-band.png", length: 1.0267, depth: 0.0678 },
  "/img/designs/necklines/nl07.png": { image: "/img/designs/necklines/nl07-band.png", length: 1.0033, depth: 0.0300 },
  "/img/designs/necklines/nl08.png": { image: "/img/designs/necklines/nl08-band.png", length: 0.9633, depth: 0.0311 },
  "/img/designs/necklines/nl09.png": { image: "/img/designs/necklines/nl09-band.png", length: 1.1812, depth: 0.0465 },
  "/img/designs/necklines/nl10.png": { image: "/img/designs/necklines/nl10-band.png", length: 0.8089, depth: 0.0322 },
  "/img/designs/necklines/nl11.png": { image: "/img/designs/necklines/nl11-band.png", length: 0.8689, depth: 0.0644 },
  "/img/designs/necklines/nl12.png": { image: "/img/designs/necklines/nl12-band.png", length: 1.0945, depth: 0.0604 },
  "/img/designs/necklines/nl13.png": { image: "/img/designs/necklines/nl13-band.png", length: 0.8400, depth: 0.0822 },
  "/img/designs/necklines/nl14.png": { image: "/img/designs/necklines/nl14-band.png", length: 0.9367, depth: 0.0767 },
};
