"use client";

import { useLayoutEffect, useMemo, useRef } from "react";
import type { Garment } from "@/lib/catalogue";
import { anchors, build, overlay } from "@/lib/garment";
import { FLAT_RATIO, buildJallabiyaFlat } from "@/lib/jallabiya-flat";
import type { Fabric } from "@/lib/loom";
import { designAsset, type PreviewDesign, type ThreadTones } from "@/lib/loom-preview";
import { stitchIn, type Stitching } from "./stitch-in";

/**
 * The garment as configured: a ghost mannequin product shot, drawn.
 *
 * The renderer returns SVG and HTML strings, so this is one of the few places
 * `dangerouslySetInnerHTML` is warranted. Every input is generated by our own
 * code from typed state, never from anything a visitor supplies.
 */
export function GarmentPreview({
  garment,
  colour,
  fabric,
  design,
  thread,
  length,
}: {
  garment: Garment;
  colour: string;
  fabric: Fabric;
  design: PreviewDesign | null;
  /** the thread the jallabiya's neckline is run in; null keeps its own colours */
  thread?: ThreadTones | null;
  /** the jallabiya's length in inches, from the Loom's Length step */
  length?: number;
}) {
  const markup = useMemo(() => {
    /* The jallabiya has its own drawing, traced from the studio's sketch,
       with the neckline stitched into it and the hem at the chosen length. */
    if (garment === "jallabiya") {
      return buildJallabiyaFlat({
        color: colour,
        fabric: fabric.id,
        neckline: designAsset(design, "neckline"),
        thread,
        length,
      });
    }
    const svg = build({ type: garment, color: colour, fabric: fabric.id });
    const a = anchors(garment);

    /* The library files a kaftan design as a pair, a band for the placket and
       a piece for the pocket; an agbada design is one chest panel. */
    let designs = "";
    if (garment === "agbada") {
      designs += overlay(a.flap, designAsset(design, "panel") ?? "");
    } else {
      const placket = designAsset(design, "placket");
      const pocket = designAsset(design, "pocket");
      if (placket) designs += overlay(a.flap, placket);
      if (pocket) designs += overlay(a.pocket, pocket);
    }
    return svg + (design ? designs : "");
  }, [garment, colour, fabric.id, design, thread, length]);

  /* A newly chosen neckline is stitched into the cloth. Only a change sews:
     the design on arrival is simply there, already made. */
  const stage = useRef<HTMLDivElement>(null);
  const seen = useRef<string | null | undefined>(undefined);
  const running = useRef<Stitching | null>(null);
  const neckline = garment === "jallabiya" ? designAsset(design, "neckline") : null;

  // a drawing rebuilt mid-stitch (the colour changed, say) picks up where the needle is
  useLayoutEffect(() => {
    running.current?.apply();
  }, [markup]);

  useLayoutEffect(() => {
    const before = seen.current;
    seen.current = neckline;
    if (before === undefined || !neckline || neckline === before) return;
    if (!stage.current || matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const run = stitchIn(stage.current, neckline, () => {
      if (running.current === run) running.current = null;
    });
    running.current = run;
    return () => {
      run.stop();
      if (running.current === run) running.current = null;
    };
  }, [neckline]);

  return (
    <div
      ref={stage}
      className="garment-stage"
      // the jallabiya's drawing is cropped tight to the garment, taller than the others
      style={garment === "jallabiya" ? { aspectRatio: FLAT_RATIO } : undefined}
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}
