"use client";

import { useMemo } from "react";
import type { Garment } from "@/lib/catalogue";
import { anchors, build, overlay } from "@/lib/garment";
import { FLAT_RATIO, buildJallabiyaFlat } from "@/lib/jallabiya-flat";
import type { Fabric } from "@/lib/loom";
import { designAsset, type PreviewDesign, type ThreadTones } from "@/lib/loom-preview";

/**
 * The garment as configured: a ghost mannequin product shot, drawn.
 *
 * The renderer returns SVG and HTML strings, so this is one of the few places
 * `dangerouslySetInnerHTML` is warranted. Every input is generated by our own
 * code from typed state, never from anything a visitor supplies.
 */
export function GarmentPreview({
  garment,
  colour,
  fabric,
  design,
  thread,
  length,
  sleeves = false,
  tassel = false,
}: {
  garment: Garment;
  colour: string;
  fabric: Fabric;
  design: PreviewDesign | null;
  /** the thread the jallabiya's neckline is run in; null keeps its own colours */
  thread?: ThreadTones | null;
  /** the jallabiya's length in inches, from the Loom's Length step */
  length?: number;
  /** the jallabiya's neckline pattern round both cuffs */
  sleeves?: boolean;
  /** a tassel at the foot of the jallabiya's neck opening */
  tassel?: boolean;
}) {
  const markup = useMemo(() => {
    /* The jallabiya has its own drawing, traced from the studio's sketch,
       with the neckline stitched into it and the hem at the chosen length. */
    if (garment === "jallabiya") {
      return buildJallabiyaFlat({
        color: colour,
        fabric: fabric.id,
        neckline: designAsset(design, "neckline"),
        thread,
        length,
        sleeves,
        tassel,
      });
    }
    const svg = build({ type: garment, color: colour, fabric: fabric.id });
    const a = anchors(garment);

    /* The library files a kaftan design as a pair, a band for the placket and
       a piece for the pocket; an agbada design is one chest panel. */
    let designs = "";
    if (garment === "agbada") {
      designs += overlay(a.flap, designAsset(design, "panel") ?? "");
    } else {
      const placket = designAsset(design, "placket");
      const pocket = designAsset(design, "pocket");
      if (placket) designs += overlay(a.flap, placket);
      if (pocket) designs += overlay(a.pocket, pocket);
    }
    return svg + (design ? designs : "");
  }, [garment, colour, fabric.id, design, thread, length, sleeves, tassel]);

  /* A chosen neckline is simply there, already sewn: picking one answers at
     once, with no stitching to wait through. */
  return (
    <div
      className="garment-stage"
      // the jallabiya's drawing is cropped tight to the garment, taller than the others
      style={garment === "jallabiya" ? { aspectRatio: FLAT_RATIO } : undefined}
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}
